In [13]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def dev_sigmoid(x):
    return x * (1-x)

In [28]:
# Input datasets
x_data = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
y_data = np.array([
    [0],
    [1],
    [1],
    [0]
])

In [33]:
x_data = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
y_data = np.array([
    [0],
    [1],
    [1],
    [1]
])

In [21]:
x_data = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
y_data = np.array([
    [0],
    [0],
    [0],
    [1]
])

In [34]:
epochs = 10000
lr = 0.1
iln, hln, oln = 2, 4, 1

In [35]:
# Random weights and bias initialization
hw = np.random.uniform(size = (iln, hln))
hb = np.random.uniform(size = (1, hln))
ow = np.random.uniform(size = (hln, oln))
ob = np.random.uniform(size = (1, oln))

In [36]:
# Trainig algorithm
for i in range(epochs):
    #Forward Propagations
    hla = np.dot(x_data, hw)
    hla += hb
    hlo = sigmoid(hla)
    
    ola = np.dot(hlo, ow)
    ola += ob
    po = sigmoid(ola)
    
    #BackPropagations
    error = y_data - po
    dpo = error * dev_sigmoid(po)
    
    ehl = dpo.dot(ow.T)
    dhl = ehl * dev_sigmoid(hlo)
    
    #Updating weights and Biases
    ow += hlo.T.dot(dpo) * lr
    ob += np.sum(dpo, axis=0, keepdims=True) * lr
    hw += x_data.T.dot(dhl) * lr
    hb += np.sum(dhl, axis=0, keepdims=True) * lr

In [26]:
print(np.round(po))

[[0.]
 [0.]
 [0.]
 [1.]]


In [27]:
print(po)

[[9.09593585e-04]
 [2.61442565e-02]
 [2.55088658e-02]
 [9.65385014e-01]]


In [32]:
print(po)

[[0.04160712]
 [0.96400687]
 [0.93516506]
 [0.06109302]]


In [37]:
print(po)

[[0.03513127]
 [0.97897205]
 [0.97958888]
 [0.9981235 ]]
